// Khordha district institutions compiled from Odisha Higher Education, SAMS,
// university, and SCTE&VT directories. The picker also accepts a custom college.
const COLLEGE_NAMES = [
  'Utkal University',
  'Rama Devi Women’s University',
  'Odisha University of Agriculture & Technology (OUAT)',
  'Odisha University of Technology and Research (OUTR)',
  'Utkal University of Culture',
  'KIIT University',
  'Siksha ‘O’ Anusandhan (SOA)',
  'KISS Deemed to be University',
  'Xavier University, Bhubaneswar',
  'IIT Bhubaneswar',
  'IIIT Bhubaneswar',
  'NISER Bhubaneswar',
  'Buxi Jagabandhu Bidyadhar (BJB) Autonomous College',
  'Ramadevi Women’s College',
  'College of Engineering Bhubaneswar',
  'Gandhi Engineering College',
  'Gandhi Institute for Technology (GIFT)',
  'Raajdhani Engineering College',
  'Nalanda Institute of Technology',
  'Aryan Institute of Engineering and Technology',
  'NM Institute of Engineering and Technology',
  'Hi-Tech Institute of Technology',
  'Jupiter Degree College',
  'NIFT Bhubaneswar',
  'Institute of Hotel Management, Bhubaneswar',
  'KIIT School of Management',
  'Xavier School of Human Resource Management',
  'All India Institute of Medical Sciences (AIIMS), Bhubaneswar',
  'ASBM University',
  'Biju Patnaik Institute of Information Technology and Management Studies (BIITM)',
  'Birla Global University',
  'Buxi Jagabandhu Bidyadhar (Autonomous) College (BJB), Bhubaneswar',
  'College of Engineering and Technology (CET), Bhubaneswar (OUTR)',
  'College of Engineering, Bhubaneswar (Koustuv Technical Campus)',
  'College of Basic Science and Humanities, OUAT',
  'College of Agriculture, OUAT, Bhubaneswar',
  'College of Agricultural Engineering and Technology, OUAT',
  'College of Community Science, OUAT',
  'College of Forestry, OUAT',
  'College of Veterinary Science and Animal Husbandry, OUAT',
  'C.V. Raman Global University',
  'C.V. Raman College of Engineering',
  'D.A.V. School of Business Management',
  'Ekamra College, Bhubaneswar',
  'Gandhi Institute for Technological Advancement (GITA)',
  'Gandhi Institute of Technology and Management (GIFT)',
  'Gandhi Engineering College (GEC), Bhubaneswar',
  'Government Polytechnic, Bhubaneswar',
  'Hi-Tech Medical College and Hospital, Bhubaneswar',
  'Institute of Technical Education and Research (ITER), Siksha O Anusandhan',
  'Institute of Management and Information Science (IMIS), Bhubaneswar',
  'Institute of Mathematics and Applications (IMA), Bhubaneswar',
  'Institute of Minerals and Materials Technology (IMMT), Bhubaneswar',
  'Kalinga Institute of Industrial Technology (KIIT)',
  'Kalinga Institute of Medical Sciences (KIMS)',
  'Kalinga Institute of Social Sciences (KISS)',
  'KIIT School of Law',
  'Kamala Nehru Women’s College, Bhubaneswar',
  'Maharishi College of Natural Law, Bhubaneswar',
  'Maharishi Women’s Degree College, Bhubaneswar',
  'National Institute of Fashion Technology (NIFT), Bhubaneswar',
  'National Institute of Social Work and Social Sciences (NISWASS)',
  'Odisha University of Agriculture and Technology (OUAT)',
  'Odisha University of Health Sciences (OUHS)',
  'Odisha University of Technology and Research (OUTR)',
  'Rama Devi Women’s University, Bhubaneswar',
  'Rajdhani College, Bhubaneswar',
  'Regional College of Management, Bhubaneswar',
  'Silicon University',
  'Sri Jayadev College of Education and Technology',
  'Utkal University, Bhubaneswar',
  'Xavier Institute of Management, Bhubaneswar (XIMB)',
  'XIM University, Bhubaneswar',
  'Biju Patnaik College of Science and Education, Bhubaneswar',
  'City Women’s Degree College, Siripur',
  'Deb Ray College, Bhubaneswar',
  'Raja Madhusudan Dev Degree College of Science and Education',
  'Sri Satyasai College for Women, Pokhariput',
  'Nalini Devi Women’s College of Teacher Education',
  'Orissa Engineering College (OEC)',
  'Trident Academy of Technology',
  'Bhubaneswar Engineering College',
  'Bhubaneswar Polytechnic, Janla',
  'Balugaon College, Balugaon',
  'Banamalipur Degree College, Banamalipur',
  'Barunei Institute of Engineering and Technology, Barunei',
  'Begunia College, Begunia',
  'Biju Patnaik Degree College of Science and Education, Bhubaneswar',
  'BRM International Institute of Technology, Rasulgarh',
  'C.V. Raman Polytechnic, Janla',
  'Capital Law College, Bhubaneswar',
  'Ekamra College, Bhubaneswar',
  'Einstein School of Engineering, Baniatangi',
  'Gandhi Institute for Education and Technology, Baniatangi',
  'Gandhi Institute for Technology (GIFT), Gangapada',
  'Gandhi Institute of Excellent Technocrats, Kantabada',
  'Ganesh Institute of Engineering and Technology Polytechnic, Andharua',
  'GEC Polytechnic, Madanpur',
  'Godabarish Mahavidyalaya, Banapur',
  'Government Polytechnic, Khordha',
  'Haldia College, Haldia',
  'International Institute of Information Technology (IIIT), Bhubaneswar',
  'Janata Degree College, Kuhudi',
  'Jatni College, Jatni',
  'Kabi Prasan Patsani Anchalika Degree College, Khordha',
  'Kali Charan Panchagarh Ananga Narendra Degree College, Bankoi',
  'KIIT Polytechnic, Bhubaneswar',
  'Koustuv School of Engineering, Bhubaneswar',
  'Krupajal Engineering School, Bhubaneswar',
  'Kunja Bihari College, Barang',
  'Kshetrabasi Dayananda Anglo Vedic College, Nirakarpur',
  'Maharaja Polytechnic, Taraboi',
  'Mahavir Engineering College, Paniora',
  'Muktapur College, Muktapur',
  'Nachuni Mahavidyalaya, Nachuni',
  'Nalini Devi Women’s College of Teacher Education, Bhubaneswar',
  'Odisha University of Technology and Research (OUTR), Bhubaneswar',
  'Odisha University of Agriculture and Technology (OUAT), Bhubaneswar',
  'Odisha University of Culture, Bhubaneswar',
  'Oxford School of Polytechnic, Balianta',
  'Paramananda College, Bolagarh',
  'Prana Nath Autonomous College, Khordha',
  'Pratap Sasana Degree College, Balakati',
  'Raghunath Degree College, Deuli',
  'Raja Madhusudan Dev Degree College of Science and Education, Patia',
  'Ramachandi Degree Mahavidyalaya, Garh Manitri',
  'Ramamani Mahavidyalaya, Kantabad',
  'Sanatan Harichandan Degree Mahavidyalaya, Madanpur',
  'Sishu Ananta Mahavidyalaya, Balipatna',
  'Sri Jagannath College, Kaipadar',
  'Synergy Polytechnic, Phulnakhara',
  'The Techno School, Patrapada',
  'Utkal University, Bhubaneswar',
  'Women’s College, Khordha',
  'Zenith Institute of Science and Technology, Jatni',
  'Other / college not listed',
];

// Keep the picker stable if an institution appears in more than one source.
export const BHUBANESWAR_COLLEGES = [...new Set(COLLEGE_NAMES)]
  .sort((a, b) => a.localeCompare(b));
